version: "3.7"

services:
  mongo:
    container_name: "tla-mongo"
    image: mongo
    volumes:
      - ./db-data/prod:/data/db
    ports:
      - 27017:27017
    restart: always
    env_file:
      - .production.env
    networks:
      - todo-list-app

  mongo-express:
    container_name: "tla-me"
    image: mongo-express
    ports:
      - 8081:8081
    restart: always
    env_file:
      - .production.env
    depends_on:
      - mongo
    networks:
      - todo-list-app

  backend:
    container_name: "tla-backend"
    image: snakpy/listlive-backend:latest
    ports:
      - 4000:4000
    env_file:
      - .production.env
    depends_on:
      - mongo
      - mongo-express
    networks:
      - todo-list-app

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json
    command: --interval 30

networks:
  todo-list-app:
